Mentoring t 44
BI-kotlin-in-action/DaeyeonKim pull request #1
Opened 2023-10-11 13:20 UTC by kim946509

알고리즘 과제 코드입니다. 감사합니다!

2023-10-12 02:03 UTC, konempty requested changes
고생하셨습니다 👍 
조금만더 수정 부탁드릴게요~!

2023-10-12 02:03 UTC, konempty commented on q1181.kt
> +    var words = ArrayList<String>()
더 코틀린스러운 코드를 위해서는 이번주에 배울 MutableList를 사용하시면 좋습니다~!

2023-10-12 02:03 UTC, konempty commented on q1181.kt
> +    val n = readLine()?.toInt()
readLn()을 쓰면 non-null로 받을수 있습니다~!

2023-10-12 02:03 UTC, konempty commented on q1181.kt
> +        word = readLine()?.toString() ?: ""
readLn의 결과가 String일거라서 toString은 없어도 될것 같아요!

2023-10-12 02:03 UTC, konempty commented on q1181.kt
> +fun merge_sort(words: ArrayList<String>, left: Int, right: Int) {
오 굿굿 언어 학습 측면에서는 소팅 구현하는거 좋습니다~!
그러나 실제 알고리즘 문제 푸실때는 요렇게 소팅 구현하시면 시간 부족하니까 
이미 정의된 함수를 사용해주세요~!

2023-10-12 02:03 UTC, konempty commented on q1181.kt
> +    merge_sort(words, 0, words.size - 1)
소트를 돌리고 중복을 제거해야 햇다면 words의 자료형이 SortedSet<String>이어도 좋을것 같아요!

2023-10-12 02:03 UTC, konempty commented on q1296.kt
> +    var teamNames: ArrayList<String> = arrayListOf<String>()
여기도 mutableList를 쓰는게 더 좋을것같아요!

2023-10-12 02:03 UTC, konempty commented on q1920.kt
> +        }
요 코드는 아래와 같이 줄일수 있을것 같아요!
```kotlin
println(if(num in arr) 1 else 0)
```

2023-10-12 02:03 UTC, konempty commented on q1920.kt
> +    size = readLine()?.toInt() ?: 0
ㅋㅋㅋ...readLn을 쓰면 전부 non-null로 쉽게 쓸수 있을것 같네요

2023-10-12 10:52 UTC, kim946509 commented on q1181.kt
> +    var words = ArrayList<String>()
넵! MutableList로 수정해 보겠습니다!

2023-10-12 10:52 UTC, kim946509 commented on q1181.kt
> +    val n = readLine()?.toInt()
감사합니다! 수정하겠습니다!

2023-10-12 10:52 UTC, kim946509 commented on q1181.kt
> +fun merge_sort(words: ArrayList<String>, left: Int, right: Int) {
넵 ㅎㅎ 감사합니다!

2023-10-12 10:53 UTC, kim946509 commented on q1181.kt
> +    merge_sort(words, 0, words.size - 1)
아 그러는 편히 훨씬 좋을것 같네요. set으로 수정해보겠습니다. 감사합니다 ㅎㅎ

2023-10-12 10:53 UTC, kim946509 commented on q1920.kt
> +        }
when을 써보고자 하는 욕심에 써봤는데 알려주신 코드가 더 깔끔하네요 ㅎㅎ 수정하겠습니다. 감사합니다!

2023-10-12 10:53 UTC, kim946509 commented on q1920.kt
> +    size = readLine()?.toInt() ?: 0
넵..ㅎㅎ 전부 수정하겠습니다.

2023-10-12 10:54 UTC, kim946509 commented on q1181.kt
> +        word = readLine()?.toString() ?: ""
넵! 수정하겠습니다. 감사합니다

2023-10-13 00:27 UTC, konempty approved these changes
고생하셨습니다 👍 👍 
리뷰가 너무 길어질것 같아서 이번주 리뷰는 요정도로 하겠습니다!
제가 이번에 리뷰드린것만 적용부탁드립니다~

2023-10-13 00:27 UTC, konempty commented on q1181.kt
> +    repeat(n ?: 0) {
n은 null일수 없기때문에 여기에서 ?: 0 는 불필요할것 같아요~!

2023-10-13 00:27 UTC, konempty commented on q1181.kt
> +    var setWords = words.toSortedSet(compareBy<String> { it.length }.thenBy { it })
words가 mutableListOf대신에 sortedSetOf를 썼다면 toSortedSet을 안해도 되겠죠?

2023-10-13 00:27 UTC, konempty commented on q1296.kt
> +    for (i in 0 until teamCount!!) {
teamCount가 null일수 없어서 어설션은 불필요 할것 같아요~!

2023-10-13 07:46 UTC, kim946509 commented on q1181.kt
> +    repeat(n ?: 0) {
감사합니다! 수정 완료하였습니다. 다음부터는 모두 고려해서 작성하겠습니다.

2023-10-13 07:46 UTC, kim946509 commented on q1181.kt
> +    var setWords = words.toSortedSet(compareBy<String> { it.length }.thenBy { it })
네! sortedSetOf 까지 사용하여 모두 작성하였습니다. 코드가 처음보다 정말 간결해졌네요..감사합니다!

2023-10-13 07:47 UTC, kim946509 commented on q1296.kt
> +    for (i in 0 until teamCount!!) {
넵 다음 부터는 null 가능성 고려하면서 코드 작성하겠습니다. 감사합니다!

2023-10-13 12:56 UTC, konempty approved these changes
앗 ㅋㅋㅋㅋ 제가 PR을 approve를 했으면 코멘트 받은것 적용후 다시 리뷰 요청이 아니라
바로 머지하시면 됩니다~!

2023-10-13 13:06 UTC, merged