Mentoring-T-60 알고리즘 과제 제출
BI-kotlin-in-action/DaeyeonKim pull request #2
Opened 2023-10-30 17:52 UTC by kim946509

Mentoring-T-60 
김대연 알고리즘 과제 제출합니다. 감사합니다!

2023-10-31 13:43 UTC, konempty requested changes
고생하셨습니다 👍 👍 
조금만더 수정 부탁드릴게요~!

2023-10-31 13:43 UTC, konempty commented on q1835.kt
> +    var cards = MutableList(n) { 0 }
이경우 굳이 MutableList로 가변성을 노출할 필요가 없을것 같아요!
아마 제가 추측하기에는 MutableList가 아니면 내부의 엘리먼트를 수정 못할것 같아서
MutableLIst를 쓰시는것 같은데 Array나 List들도 엘리먼트 추가/삭제만 불가능 할뿐
엘리먼트 수정은 가능합니다~!
저라면 요 상황에서는 IntArray를 쓰시는걸 추천해드려요

2023-10-31 13:43 UTC, konempty commented on q1835.kt
> +    for (i in 1 until n + 1) {
이경우 until보다는
```kotlin
for (i in 1 .. n){
```
이 더 적절해 보입니다~!

2023-10-31 13:43 UTC, konempty commented on q1835.kt
> +        print("${cards[i]} ")
요 경우 for문을 쓰지 않고 아래와 같이 joinString이라는 코틀린의 확장함수를 쓰시는게 더 코틀린 스러운 코드입니다!
print(cards.joinString(" "))

2023-10-31 13:43 UTC, konempty commented on q2628.kt
> +    y.sort()
sort가 되는걸 원했다면 mutableListOf 대신 sortedSetOf를 쓰는게 더 효율적이었을것 같아요!

2023-10-31 13:43 UTC, konempty commented on q8979.kt
> +    var countries = ArrayList<Country>()
요기는 mutableListOf가 더 나을것 같아요!

2023-10-31 13:43 UTC, konempty commented on q8979.kt
> +    }
여기 5줄은 코틀린의 count라는 확장함수를 통해 한줄로 줄일수 있어요
```kotlin
    val targetRank = countries.count { target.compare(it) == -1 }
```

2023-10-31 13:43 UTC, konempty commented on q8979.kt
> +    var target = countries.find { it.id == targetCountryId } ?: Country(0, 0, 0, 0)
요 target은 가변성을 제한하기 위해 val이 좋을것 같아요! ㅋㅋㅋ

2023-10-31 13:43 UTC, konempty commented on q9012.kt
> +    var pair: Boolean
```kotlin
    var balance: Int
    var input: String
    var pair: Boolean
```

요 3개 변수는 repeat블럭 내부에서만 사용되는데 불필요하게 넓은 생명 범위를 가지고 있고 가변성을 노출하고 있는데
만약 repaet블럭 내부에서 선언한다면 일부는 val로 바꿀수 있지 않을까요??

그리고 test는 확실히 val로 바꿀수 있어 보이네요 ㅋㅋㅋ

2023-11-01 01:13 UTC, kim946509 commented on q1835.kt
> +    var cards = MutableList(n) { 0 }
넵! 수정이 이루어지기 때문에 MutableList를 사용해야 한다고 생각했었습니다. IntArray로 수정하겠습니다!

2023-11-01 01:15 UTC, kim946509 commented on q1835.kt
> +    for (i in 1 until n + 1) {
넵. until을 자주 사용하였더니 이번에도 until을 사용했네요. 고려하면서 작성하겠습니다! 감사합니다.

2023-11-01 01:16 UTC, kim946509 commented on q1835.kt
> +        print("${cards[i]} ")
넵! 확장 함수들을 잘 활용하겠습니다. 감사합니다!

2023-11-01 01:16 UTC, kim946509 commented on q2628.kt
> +    y.sort()
넵! 감사합니다. 수정하겠습니다.

2023-11-01 01:17 UTC, kim946509 commented on q8979.kt
> +    var countries = ArrayList<Country>()
넵! mutableList로 수정하겠습니다

2023-11-01 01:18 UTC, kim946509 commented on q8979.kt
> +    }
넵! 위와 마찬가지로 확장함수를 활용하면 정말 코드가 간결해지는 것 같네요. 최대한 활용해보려고 노력하겠습니다! 감사합니다.

2023-11-01 01:18 UTC, kim946509 commented on q8979.kt
> +    var target = countries.find { it.id == targetCountryId } ?: Country(0, 0, 0, 0)
넵! 가변성을 더 신경 써서 코드 작성하겠습니다. 감사합니다.

2023-11-01 01:24 UTC, kim946509 commented on q9012.kt
> +    var pair: Boolean
repeat블럭 내부에서 변수를 선언하면 반복될 때 마다 변수를 생성하여 비효율적이라고 생각하여 repeat블럭 외부에서 변수를 선언하였는데 이는 잘못된 생각일까요?

2023-11-01 11:15 UTC, konempty commented on q9012.kt
> +    var pair: Boolean
대연님 의견도 일리가 있습니다 ㅋㅋㅋ
하지만 3개정도의 변수를 여러번 재생성 하는건 그닥 성능에 차이가 없고
심지어 primitive는 JVM의 GC를 사용하는게 아닌 바로 메모리 해제를 시키기 때문에
메모리 관련 이슈도 없습니다~!
따라서 크게 비효율적이지는 않구요
코드 관리 측면에서 저렇게 생명주기가 불필요하게 넓은 변수가 있다면 좋지 않기 때문에
제 개취는 저런 변수는 블록에 넣는걸 선호합니다!

2023-11-01 11:37 UTC, konempty requested changes
진짜 조금만더 수정부탁드릴게요...! ㅎㅎㅎ

2023-11-01 11:37 UTC, konempty commented on q1835.kt
> +    var cards = Array<Int>(n) { 0 }
요기에는 intArray를 쓰는게 좋을것 같습니다~!

2023-11-01 11:37 UTC, konempty commented on q2628.kt
> +    x.add(0)
0이 기본적으로 들어가야 한다면 선언과 동시에 넣는게 좋습니다!
```kotlin
    val y = sortedSetOf(0) // 가로 자른 위치
    val x = sortedSetOf(0) // 세로 자른 위치
```

2023-11-01 11:37 UTC, konempty commented on q2628.kt
> +    for (i in 0 until y.size - 1) {
for (i in 1 until y.size) 로 하고
아래에서 
var area = (y.elementAt(i) - y.elementAt(i - 1)) * (x.elementAt(j) - x.elementAt(j - 1))
요렇게 하면 - 1 연산을 조금이라도 덜 할수 있지 않을까요?? ㅎㅎ

2023-11-01 11:37 UTC, konempty commented on q8979.kt
> +    var countries = mutableListOf<Country>()
요 두개 변수는 val로 해도 될것 같아요~!

2023-11-01 11:37 UTC, konempty commented on q8979.kt
> +    fun compare(other: Country): Int {
<img width="419" alt="스크린샷 2023-11-01 오후 8 22 45" src="https://github.com/BI-kotlin-in-action/DaeyeonKim/assets/44064530/1d043b6c-e6b6-47a3-8f74-72a750d77f92">

코틀린에서 요렇게 연산자 메소드를 정의할 수 있는데 이렇게 한다면

아래에서 
    targetRank = countries.count { target > it }
와 같이 부등호로 비교할수 있습니다~!

2023-11-01 11:37 UTC, konempty commented on q8979.kt
> +    var bronze: Int
요 변수 4개는 repeat블록 내부에서만 쓰는게 좋을것 같아요~!

2023-11-01 11:37 UTC, konempty commented on q2628.kt
> +    var area = 0 // 사각형 넓이
ㅋㅋㅋ 요 area변수는 선언만 하고 실제로 사용은 안되네요

2023-11-01 11:37 UTC, konempty commented on q2628.kt
> +            var area = (y.elementAt(i + 1) - y.elementAt(i)) * (x.elementAt(j + 1) - x.elementAt(j))
요 area는 var일 필요가 없어보이구요 ㅋㅋㅋ

2023-11-01 11:37 UTC, konempty commented on q8979.kt
> +    var targetCountryId = input.get(1).toInt()
요 2줄은 아래와 같이 한줄로도 줄일수 있어요~!

    val (n, targetCountryId) = readln().split(" ").map { it.toInt() }

2023-11-01 11:37 UTC, konempty commented on q8979.kt
> +    var targetRank = 0
요 변수를 선언과 할당을 나누신 이유가 있을까요??
아래쪽에서
val targetRank = countries.count { target.compare(it) == -1 }
요렇게 한줄로 하는게 깔끔하지 않았을까요?

2023-11-01 11:37 UTC, konempty commented on q9012.kt
> +                pair = false
어차피 for문 밖으로 나가면 pair는 false로 값이 할당 될텐데 여기서 할당 안해줘도 되지 않을까요?? ㅋㅋㅋ

2023-11-01 11:37 UTC, konempty commented on q9012.kt
> +        println(if (pair) "YES" else "NO")
지금보니까 pair라는 변수 없이
println(if (balance != 0) "YES" else "NO")
을 해도 동일한 효과를 나타낼것 같아요! ㅋㅋㅋ

2023-11-01 12:22 UTC, kim946509 commented on q9012.kt
> +    var pair: Boolean
아 그렇군요 ㅎㅎ 답변 감사합니다!

2023-11-01 13:03 UTC, kim946509 commented on q1835.kt
> +    var cards = Array<Int>(n) { 0 }
넵! Array<Int>와 차이가 없을 줄 알았는데 찾아보니 차이가 있었네요. 감사합니다!

2023-11-01 13:03 UTC, kim946509 commented on q2628.kt
> +    x.add(0)
넵! 감사합니다.

2023-11-01 13:04 UTC, kim946509 commented on q2628.kt
> +    for (i in 0 until y.size - 1) {
넵 ㅠ 확실히 그렇네요. 효율적으로 짜보려고 더 노력해야 할 것 같습니다. 감사합니다!

2023-11-01 13:04 UTC, kim946509 commented on q8979.kt
> +    var countries = mutableListOf<Country>()
넵! 다음 번에는 이러한 피드백은 안 나오도록 노력하겠습니다!

2023-11-01 13:05 UTC, kim946509 commented on q8979.kt
> +    fun compare(other: Country): Int {
넵! 연산자 메소드 정의하니 간결해지고 직관적으로 보기 쉬워지네요. 감사합니다!

2023-11-01 13:09 UTC, kim946509 commented on q8979.kt
> +    var targetCountryId = input.get(1).toInt()
넵! 정말 간결해질 수 있는 부분이 많네요.ㅎㅎ 감사합니다

2023-11-01 13:09 UTC, kim946509 commented on q8979.kt
> +    var targetRank = 0
targetRank는 굳이 나눌 필요가 없었는데 나눈 것 같습니다. 수정하겠습니다. 감사합니다!

2023-11-01 13:11 UTC, kim946509 commented on q9012.kt
> +                pair = false
넵! 어차피 밑에서도 false로 할당되어서 불필요한 부분이네요 ㅠ 감사합니다!

2023-11-01 13:11 UTC, kim946509 commented on q9012.kt
> +        println(if (pair) "YES" else "NO")
오.. 그렇네요. 뭔가 이런 문제에서는 항상 boolean 변수를 사용 해왔어서 당연하게 사용했던 것 같습니다. 감사합니다!

2023-11-01 14:00 UTC, konempty approved these changes
크 고생하셨습니다 👍 👍 
코멘트 하나만 적용후 머지 하셔도 좋을것 같습니다~!

2023-11-01 14:00 UTC, konempty commented on q2628.kt
> +    x.add(size[0])
지금 보니까 size도 프로그램 시작할때 받는 값이니까
    val y = sortedSetOf(0, size[1]) // 가로 자른 위치
    val x = sortedSetOf(0, size[0]) // 세로 자른 위치
요렇게 까지 줄일수 있겠네요 ㅋㅋㅋ

2023-11-01 15:12 UTC, kim946509 commented on q2628.kt
> +    x.add(size[0])
아 미리 받아도 상관 없는 값이네요.ㅠ 코멘트 해주셔서 정말 많이 배우고 있습니다. 감사합니다! 수정 후 merge 하겠습니다!

2023-11-01 15:13 UTC, merged